services:
- postgresql
before_install:
- gem update --system
- gem install bundler:1.17.3
before_script:
- cp config/database.yml.travis config/database.yml
- cp .env.travis .env
- bundle exec rails db:create 
- bundle exec rails db:schema:load
dist: trusty
language: ruby
rvm:
- 2.5.5
script:
- bundle exec rspec
env:
  global:
    - secure: J/zN5/Gh5MOqyZF4SagO8zHJ6N92WdS/LD49lyiJ3IU6NkdYyxWuHtwdDwAxP5OuX3xnFDoOKtCGaGmu5Y/pmZb7n/Ib4eDZYts5Jm57+/n0uNyc5mOpV8ipr34lObiUDqOdh0yu15gDqwG5wm7GtkB0NKpgdbJdobt/StMTYd6LhlVT8WTLBBkCyg7j3u3x1sJMJT5QfPzzgzFHxTtfd8gA9su8uhcSPqT+aywSJzGBa9L5sjtlY7kgke63ka7l4f6FASIZsKjOMkHqEZsjQiwKGCpNXao1iBtPoQy3KgP6Tfa171bWX7ygf7ROpTxE8TADSbADkmeCQZQWbm0OomAdnpf/dj8tJdNF/6oWDCyDqTLIT1ZKG7MQes61RRmzg8sPJplblk5dbq7gRhgAEUmQL6UnpYOC1Cr+Ax1Uu8/WtJ+KnxBqvHcoqGuYS4l+VUYC0fV8RhDzmV2ik6FmUmNirFvYyS2Y8AFSxEccWmlmaVb9bpJOev00YkDovWNq8ASWOcLPR/QjvVDkttmM6Z0/nT+eMMzWrYK+8MBvbWwDevO63zHkSwVK6nE7YDH8c75KZBzgU3zc/53KaCM4pFV3tY8BmHTSZojEip5UDA9kT5a4LbKMILAAmjhafNEDFmUutss75+UF+Ek+SsJSrkqP4Np/M8yFmPfXgcgUvmk=
    - RAILS_ENV=test
